baseURL = "https://cise.ufl.edu/~jack.polk/"
languageCode = "en-us"
title = "jfp"
theme="archie"
copyright = "Â© jfp"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="auto"
featherIconsCDN=true
subtitle = "Catch up with CISE's developers and follow our progress on various projects!"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/decaby7e"

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Files"
url = "/files"
weight = 5
